export const SELECTED_COUNTRY_CHANGE = 'SELECTED_COUNTRY_CHANGE';
export const STATISTIC_CHART_DATA_SET = 'STATISTIC_CHART_DATA_SET';
export const SET_YEARS_RANGE_SLIDER_SET = 'SET_YEARS_RANGE_SLIDER_SET';
