export const UFO_STATISTIC_DEFAULT_START_STOP_YEARS_RANGE = {
  start: 1906,
  stop: 2014
};

export const UFO_STATISTIC_DEFAULT_ACTIVE_YEARS_RANGE = [1906, 2014];

export default {
  UFO_STATISTIC_DEFAULT_ACTIVE_YEARS_RANGE,
  UFO_STATISTIC_DEFAULT_START_STOP_YEARS_RANGE
};
